### ISSUE TITLE
Embedded?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sinshu/rustysynth#14]
This is awesome!

Does this work on embedded / microcontrollers ? Like Raspberry Pi Pico or something?

What's the smallest/simplest chip you've run this on?

**Comment by sinshu** [comment]
Thanks 😄
However, answering that question is difficult because I have no experience with embedded systems. Nevertheless, since this library uses only the standard library of Rust, it should work in any environment where a standard Rust program operates. As for environments where even the standard library is not usable, honestly, I am not sure 😖
