### ISSUE TITLE
Bug: Panic with specific soundfont & midi

### ISSUE THREAD

**Issue by sevonj** [sinshu/rustysynth#22]
While building my midi player, I've been testing a lot of midi files and soundfonts. I found a combination that panics immediately.

- [GeneralTrash Soundfont](https://musical-artifacts.com/artifacts/1136)
- [Zelda2-PalWin.mid](https://vgmusic.com/file/2f720f3edaa7d2ca9939aa810cdace41.html#disqus_thread)

GeneralTrash plays other songs just fine, and the midi also plays on other soundfonts.

I can produce this crash on both linux and windows builds of my program. I was also able to reproduce it on the RustySynth example program:

```zsh
➜  rustysynth git:(main) ✗ cargo run
   Compiling workspace v0.1.0 (/home/username/Documents/Projects/rustysynth/workspace)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.22s
     Running `target/debug/workspace`
thread 'main' panicked at rustysynth/src/oscillator.rs:150:17:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
https://github.com/sinshu/rustysynth/blob/8518b5ea7334c1832bf518e8456d3adb8ec756a3/rustysynth/src/oscillator.rs#L146-L152

I haven't yet looked into how RustySynth works, so I can't really tell what causes this to underflow, and if the files I'm trying to play are up to spec.

**Comment by sinshu** [comment]
Thanks for the report 😊

I checked whether the combination of that SoundFont and MIDI file causes a crash in the [C# version](https://github.com/sinshu/meltysynth/) as well. As a result, I confirmed that it also crashes in the C# version. Upon investigating the cause, I found that the oscillator attempts to access data outside the waveform's range when playing an instrument called "Percussive Saw Wave."

When I examined the parameters of the problematic instrument in a SoundFont editor, it appeared that abnormal values were set for the waveform loop range. In the image below, you can see that the parameters offsetting the loop range are set to large negative values, which is incorrect.

![image](https://github.com/user-attachments/assets/e8aee7b2-1fd3-4e68-9b7d-c6965be37f92)

In the Rust version, the crash seems to occur because these abnormal values cause the loop's end position to come before the start position, resulting in `usize` becoming a negative value. In fact, this instrument couldn't even be played in the SoundFont editor.

Since the issue is caused by incorrect parameters in the SoundFont, there is little that can be done on the RustySynth side. While one option could be to suppress the error, I believe the correct behavior is for it to panic in this case 😖

**Comment by sevonj** [comment]
Thanks for the fast reply, and explaining it in detail.

I looked up the offending instrument in [Polyphone](https://github.com/davy7125/polyphone), which seems to somehow come up with a loop range that fits within the sample length.

![image](https://github.com/user-attachments/assets/1980cf74-7022-443c-ae47-f87d3fc7f594)

I would expect the font to be the culprit, but since the editor shows a correct looking range, could it be that something is missing? I've been reading the code and specification, but I can't say anything useful right now.

**Comment by sinshu** [comment]
The loop offset is a feature that is added to the displayed loop range at runtime. Therefore, the loop end will be rolled back beyond the starting point of the sample.

**Comment by sevonj** [comment]
> correct looking range
> 2532-26554

My mistake there was to assume that this included the loop offsets, but it is instead result of subtracting the addresses.

```
name:                Stacked Saw-C4
sample_start: 7824431
sample_end:   7851257
loop_start:   7826963
loop_end:     7850985

(edit: whoops, I named these wrong)
```

So this is in fact not a bug, but for the sake of error tolerance, could this be checked in the constructor, so I can safely catch it from SoundFont::new() result?

**Comment by sinshu** [comment]
Here’s my attempt to add a sanity check in this commit. I haven’t written Rust in a long time, so I’m not sure if this is the best way to write it nowadays. If there’s a better way to do it, please let me know.
d3cd161b01c19f7d68d231e5bf237b5b44dad0de

**Comment by sinshu** [comment]
@sevonj 
I updated the library. Thanks for the PR 😁
